FROM resin/%%RESIN_MACHINE_NAME%%-python:2.7

LABEL maintainer="Tate Berenbaum <tate@arceum.co>"

WORKDIR /usr/src/app

COPY ./requirements.txt /requirements.txt
RUN pip install --upgrade pip && pip install -r /requirements.txt

COPY . ./

#switch on systemd init system in container
ENV INITSYSTEM on

CMD ["python", "main.py"]